# Generated by Django 3.1.3 on 2020-11-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('business_id', models.CharField(max_length=255, unique=True)),
                ('company_form', models.CharField(max_length=255)),
                ('business_line', models.CharField(max_length=255)),
                ('registration_date', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('postcode', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=255)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
